version: "3.9"
    
services:
  mySql:
    image: mysql:5.7
#    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./respaldo:/home/respaldo
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
        - 3306:3306
    
volumes:
  db_data: {}
